import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";

import { ApiError, api } from "../../lib/api";
import type { Lexeme, LexemeSummary, Mistake, PracticeItem, PracticeResponse, PracticeSession, ReviewCard } from "../../lib/api";

function errorMessage(error: unknown) {
  if (error instanceof ApiError && error.code === "REVIEW_REVISION_CONFLICT") return "Thẻ này đã được cập nhật ở nơi khác. Hãy tải lại hàng đợi.";
  if (error instanceof ApiError && error.code === "SESSION_EXPIRED") return "Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại.";
  return "Không thể lưu thay đổi. Vui lòng thử lại.";
}

function Notice({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "error" | "success" }) {
  const style = tone === "error" ? "border-seal bg-seal-soft text-seal" : tone === "success" ? "border-jade bg-jade-soft text-jade" : "border-card-border bg-paper-raised text-ink-muted";
  return <p role={tone === "error" ? "alert" : "status"} className={`rounded-paper border p-4 text-sm leading-relaxed ${style}`}>{children}</p>;
}

function AudioControl({ url, label }: { url: string | null; label: string }) {
  const [failed, setFailed] = useState(false);
  if (!url) return <p className="text-sm text-ink-muted">Âm thanh cho “{label}” hiện chưa khả dụng.</p>;
  return <div className="flex flex-wrap items-center gap-3"><button type="button" className="focus-paper inline-flex size-control items-center justify-center rounded-full border border-ink" onClick={(event) => (event.currentTarget.nextElementSibling as HTMLAudioElement).play().catch(() => setFailed(true))} aria-label={`Nghe ${label}`}>▶</button><audio preload="none" src={url} onError={() => setFailed(true)} /><span className="text-sm text-ink-muted">Nghe phát âm</span>{failed && <span className="text-sm text-seal">Không thể phát âm thanh.</span>}</div>;
}

export function VocabularyPage() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<LexemeSummary[]>([]); const [selected, setSelected] = useState<Lexeme>(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { const value = query.trim(); if (!value) { setResults([]); setSelected(undefined); return; } const timer = window.setTimeout(() => { setLoading(true); setError(""); api<{ lexemes: LexemeSummary[] }>(`/lexemes?q=${encodeURIComponent(value)}`).then((response) => setResults(response.lexemes)).catch((reason) => setError(errorMessage(reason))).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [query]);
  async function select(id: string) { setError(""); try { setSelected(await api<Lexeme>(`/lexemes/${id}`)); } catch (reason) { setError(errorMessage(reason)); } }
  async function addReview() { if (!selected) return; setNotice("Đang thêm vào ôn tập…"); try { await api("/reviews/cards", { method: "POST", body: JSON.stringify({ lexeme_id: selected.id, direction: "recognition" }) }); setNotice("Đã thêm từ này vào hàng đợi ôn tập."); } catch (reason) { setNotice(errorMessage(reason)); } }
  return <section className="mx-auto max-w-study space-y-5"><div><p className="text-meta text-ink-muted">Từ vựng</p><h1 className="text-3xl font-bold">Tra cứu từ vựng</h1><p className="mt-2 leading-relaxed text-ink-muted">Tìm bằng Hán tự, pinyin hoặc nghĩa tiếng Việt.</p></div><label className="block font-semibold">Tìm từ<input className="focus-paper mt-2 min-h-control w-full rounded-paper border border-card-border bg-paper-raised px-3" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ví dụ: nǐ hǎo, xin chào, 你好" /></label>{loading && <Notice>Đang tìm từ…</Notice>}{error && <Notice tone="error">{error}</Notice>}{query.trim() && !loading && results.length === 0 && !error && <Notice>Không tìm thấy từ vựng đã xuất bản phù hợp.</Notice>}<ul className="space-y-2">{results.map((lexeme) => <li key={lexeme.id}><button type="button" onClick={() => select(lexeme.id)} className="focus-paper w-full rounded-paper border border-card-border bg-paper-raised p-4 text-left"><span lang="zh-Hans" className="font-hanzi text-hanzi-inline font-medium">{lexeme.hanzi}</span><span lang="zh-Latn-pinyin" className="ml-2 font-pinyin text-sm">{lexeme.pinyin}</span><span className="mt-1 block text-sm text-ink-muted">{lexeme.vietnamese_gloss}</span></button></li>)}</ul>{selected && <article className="space-y-4 border-y border-line py-5"><div><p lang="zh-Hans" className="font-hanzi text-3xl font-medium">{selected.hanzi}</p><p lang="zh-Latn-pinyin" className="font-pinyin text-lg">{selected.pinyin}</p><p className="mt-1 text-ink-muted">{selected.vietnamese_gloss}</p></div><AudioControl url={selected.audio_url} label={selected.hanzi}/><div className="border-l-2 border-line pl-4"><p lang="zh-Hans" className="font-hanzi text-hanzi-inline">{selected.example_hanzi}</p><p lang="zh-Latn-pinyin" className="font-pinyin text-sm">{selected.example_pinyin}</p><p className="mt-1 text-sm text-ink-muted">{selected.example_translation}</p></div><button type="button" className="focus-paper min-h-control rounded-paper border border-ink px-5 py-3 text-sm font-semibold" onClick={addReview}>Thêm vào ôn tập</button>{notice && <Notice tone={notice.startsWith("Đã") ? "success" : "neutral"}>{notice}</Notice>}</article>}</section>;
}

export function ReviewPage() {
  const [cards, setCards] = useState<ReviewCard[]>([]); const [revealed, setRevealed] = useState(false); const [state, setState] = useState("loading"); const [error, setError] = useState("");
  async function load() { setState("loading"); setError(""); try { const response = await api<{ cards: ReviewCard[] }>("/reviews/due"); setCards(response.cards); setRevealed(false); setState("ready"); } catch (reason) { setError(errorMessage(reason)); setState("error"); } }
  useEffect(() => { void load(); }, []);
  async function grade(rating: "again" | "success") { const card = cards[0]; if (!card) return; setState("saving"); try { await api("/reviews/events", { method: "POST", body: JSON.stringify({ card_id: card.id, client_event_id: crypto.randomUUID(), expected_revision: card.revision, rating }) }); await load(); } catch (reason) { setError(errorMessage(reason)); setState("error"); } }
  const card = cards[0];
  return <section className="mx-auto max-w-study space-y-5"><div><p className="text-meta text-ink-muted">Ôn tập</p><h1 className="text-3xl font-bold">Ôn đúng lúc</h1></div>{state === "loading" && <Notice>Đang tải hàng đợi ôn tập…</Notice>}{error && <Notice tone="error">{error} <button className="focus-paper font-semibold underline" onClick={load}>Tải lại</button></Notice>}{state === "ready" && !card && <Notice>Không có thẻ nào đến hạn. Bạn có thể thêm từ từ trang Tra cứu.</Notice>}{card && <article className="space-y-5"><p className="text-sm text-ink-muted">{card.direction === "recognition" ? "Nhìn từ, nhớ nghĩa" : "Nhìn nghĩa, nhớ từ"}</p><div className="rounded-paper border border-card-border bg-paper-raised p-5"><p lang="zh-Hans" className="font-hanzi text-4xl font-medium">{card.direction === "recognition" ? card.hanzi : "?"}</p><p lang="zh-Latn-pinyin" className="mt-2 font-pinyin text-lg">{card.direction === "recognition" ? card.pinyin : card.meaning}</p>{revealed && <p className="mt-4 border-t border-line pt-4 text-ink-muted">{card.direction === "recognition" ? card.meaning : `${card.hanzi} · ${card.pinyin}`}</p>}</div>{!revealed ? <button className="focus-paper min-h-control rounded-paper border border-ink px-5 py-3 text-sm font-semibold" onClick={() => setRevealed(true)}>Hiện đáp án</button> : <div className="flex flex-wrap gap-3"><button disabled={state === "saving"} className="focus-paper min-h-control rounded-paper border border-seal px-5 py-3 text-sm font-semibold text-seal disabled:opacity-60" onClick={() => grade("again")}>↻ Chưa nhớ</button><button disabled={state === "saving"} className="focus-paper min-h-control rounded-paper border border-ink bg-ink px-5 py-3 text-sm font-semibold text-paper disabled:opacity-60" onClick={() => grade("success")}>✓ Đã nhớ</button></div>}</article>}</section>;
}

export function PracticePage() {
  const [items, setItems] = useState<PracticeItem[]>([]); const [session, setSession] = useState<PracticeSession>(); const [answer, setAnswer] = useState(""); const [result, setResult] = useState<PracticeResponse>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [composing, setComposing] = useState(false);
  useEffect(() => { api<{ items: PracticeItem[] }>("/practice-items").then((response) => setItems(response.items)).catch((reason) => setError(errorMessage(reason))); }, []);
  async function begin(item: PracticeItem) { setError(""); try { const next = await api<PracticeSession>("/practice-sessions", { method: "POST", body: JSON.stringify({ item_ids: [item.item_id] }) }); setSession(next); setAnswer(""); setResult(undefined); } catch (reason) { setError(errorMessage(reason)); } }
  async function submit(event: FormEvent) { event.preventDefault(); const item = session?.items[0]; if (!session || !item || !answer || composing) return; setSaving(true); setError(""); try { setResult(await api<PracticeResponse>(`/practice-sessions/${session.id}/responses`, { method: "POST", body: JSON.stringify({ item_revision_id: item.revision_id, answer: { selected_option_id: answer } }) })); } catch (reason) { setError(errorMessage(reason)); } finally { setSaving(false); } }
  const item = session?.items[0];
  return <section className="mx-auto max-w-study space-y-5"><div><p className="text-meta text-ink-muted">Luyện tập</p><h1 className="text-3xl font-bold">Luyện theo chủ đề</h1></div>{error && <Notice tone="error">{error}</Notice>}{!session && (items.length === 0 ? <Notice>Chưa có bài luyện đã xuất bản.</Notice> : <ul className="space-y-2">{items.map((candidate) => <li key={candidate.item_id}><button type="button" className="focus-paper w-full rounded-paper border border-card-border bg-paper-raised p-4 text-left" onClick={() => begin(candidate)}><span className="font-semibold">{candidate.topic || "Bài luyện"}</span><span className="ml-2 text-sm text-ink-muted">{candidate.skill}</span></button></li>)}</ul>)}{item && <form onSubmit={submit} className="space-y-5"><fieldset><legend className="font-semibold">{item.prompt.text ?? "Chọn đáp án phù hợp"}</legend>{item.prompt.audio_url && <audio className="mt-3 w-full" controls preload="none" aria-label="Nghe câu hỏi" src={item.prompt.audio_url} />}<div className="mt-3 space-y-2">{item.options.map((option) => <label key={option.id} className={`flex min-h-control cursor-pointer items-center gap-3 rounded-paper border p-3 ${answer === option.id ? "border-ink bg-paper-raised" : "border-card-border"}`}><input type="radio" name="answer" checked={answer === option.id} onChange={() => setAnswer(option.id)} onCompositionStart={() => setComposing(true)} onCompositionEnd={() => setComposing(false)} />{option.text}</label>)}</div></fieldset><button disabled={!answer || saving || composing} className="focus-paper min-h-control rounded-paper border border-ink bg-ink px-5 py-3 text-sm font-semibold text-paper disabled:bg-ink-muted">{saving ? "Đang lưu…" : "Kiểm tra đáp án"}</button>{result && <Notice tone={result.correct ? "success" : "error"}>{result.correct ? "✓ Đúng." : "✕ Chưa đúng."} Lần thử {result.attempt_number}. {result.explanation}</Notice>}</form>}</section>;
}

export function MistakesPage() {
  const [mistakes, setMistakes] = useState<Mistake[]>([]); const [error, setError] = useState("");
  async function load() { try { setMistakes((await api<{ mistakes: Mistake[] }>("/me/mistakes")).mistakes); } catch (reason) { setError(errorMessage(reason)); } }
  useEffect(() => { void load(); }, []);
  async function resolve(mistake: Mistake) { try { await api(`/me/mistakes/${mistake.id}`, { method: "PATCH", body: JSON.stringify({ state: mistake.state === "open" ? "resolved" : "open" }) }); await load(); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="mx-auto max-w-study space-y-5"><div><p className="text-meta text-ink-muted">Sổ lỗi</p><h1 className="text-3xl font-bold">Những câu cần xem lại</h1></div>{error && <Notice tone="error">{error}</Notice>}{mistakes.length === 0 ? <Notice>Chưa có lỗi nào được lưu từ bài luyện.</Notice> : <ul className="space-y-3">{mistakes.map((mistake) => <li className="rounded-paper border border-card-border bg-paper-raised p-4" key={mistake.id}><p>{mistake.prompt.text ?? "Nội dung câu hỏi hiện không còn khả dụng."}</p><p className="mt-2 text-sm text-ink-muted">{mistake.explanation}</p><p className={`mt-3 text-sm font-semibold ${mistake.state === "open" ? "text-seal" : "text-jade"}`}>{mistake.state === "open" ? "✕ Chưa giải quyết" : "✓ Đã giải quyết"}</p><button className="focus-paper mt-3 min-h-control rounded-paper border border-ink px-4 py-2 text-sm font-semibold" onClick={() => resolve(mistake)}>{mistake.state === "open" ? "Đánh dấu đã xem lại" : "Mở lại"}</button></li>)}</ul>}</section>;
}

export function PronunciationPage() {
  return <section className="mx-auto max-w-study space-y-5"><p className="text-meta text-ink-muted">Phát âm</p><h1 className="text-3xl font-bold">Luyện phát âm nền tảng</h1><Notice>Chưa có bài phát âm đã được giáo viên duyệt và có quyền sử dụng âm thanh. Khi nội dung được xuất bản, các bài nghe–đối chiếu sẽ xuất hiện tại đây.</Notice></section>;
}
