// Generated by go run ./cmd/editorial-types. Do not edit.
export type Reference = {
  asset_id: string;
  page: number;
};
export type Audio = {
  clip_id: string;
  block_index: number;
};
export type Option = {
  id: string;
  text: string;
};
export type LexemeBody = {
  sense_key: string;
  hanzi: string;
  pinyin: string;
  vietnamese_gloss: string;
  example_hanzi: string;
  example_pinyin: string;
  example_translation: string;
};
export type Body = {
  lexeme: LexemeBody | null;
  title: string;
  unit_id: string;
  position: number;
  slug: string;
  blocks: unknown;
  prompt: string;
  options: Array<Option>;
  answer: string;
  explanation: string;
  topic: string;
  skill: string;
  sources: Array<Reference>;
  audio: Array<Audio>;
};
export type Draft = {
  kind: string;
  course_id: string;
  body: Body;
};
export type Revision = {
  id: string;
  document_id: string;
  kind: string;
  course_id: string;
  revision_number: number;
  version: number;
  state: string;
  author_id: string;
  body: Body;
};
export type Change = {
  version: number;
  action: string;
  body: Body | null;
  evidence: string;
  language: boolean;
  key: boolean;
  rights: boolean;
};
export type AssetInput = {
  title: string;
  creator: string;
  provenance: string;
  rights_status: string;
  permission_evidence: string;
  attribution: string;
  usage_scope: string;
  page_count: number;
  data: string;
};
export type Asset = {
  id: string;
  title: string;
  creator: string;
  provenance: string;
  rights_status: string;
  permission_evidence: string;
  attribution: string;
  usage_scope: string;
  checksum: string;
  media_type: string;
  size_bytes: number;
  duration_ms: number;
  page_count: number;
};
export type ClipInput = {
  asset_id: string;
  start_ms: number;
  end_ms: number;
  label: string;
};
export type Clip = {
  id: string;
  asset_id: string;
  start_ms: number;
  end_ms: number;
  label: string;
};
export type ImportRow = {
  external_id: string;
  draft: Draft;
};
export type Batch = {
  format: string;
  name: string;
  rows: Array<ImportRow>;
};
export type RowError = {
  row: number;
  external_id: string;
  code: string;
};
export type Validation = {
  id: string;
  checksum: string;
  errors: Array<RowError>;
  count: number;
};
